### ISSUE TITLE
어떻게 jar 파일을 받을수 있나요?

### ISSUE THREAD

**Issue by inchan1832** [noonmaru/inv-captive#15]
최대한 자세하게 설명 부탁드려요

**Comment by devil0414** [comment]
일단 페이퍼서버를 [이 링크](https://papermc.io/ci/job/Paper-1.16/253/artifact/paperclip.jar)에서 다운로드해서 서버 빌드하세요.
불편한 동거 플러그인은 [이 링크](https://github.com/noonmaru/inv-captive/releases/download/0.0.1/InvCaptive.jar)로 들어가서 다운로드하시면 됩니다. 
그리고 [이 링크](https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.20/Kotlin.jar)로 kotlin플러그인을 다운로드하시고 [이 링크](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar)에서 protocollib플러그인을 다운로드하세요. 그 후에 서버 내의 plugins폴더에 집어넣으시면 됩니다.
그 후 서버 내에서 /captive 명령어를 실행하시면 됩니다.

**Comment by qogusdn1017** [comment]
작동되면 이슈 닫아주세요.

**Comment by inchan1832** [comment]
[11:12:06 INFO]: Made YouTube_Inix a server operator
[11:12:07 INFO]: YouTube_Inix issued server command: /captive
[11:12:07 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'captive' in plugin InvCaptive v0.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-342]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-342]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-342]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.noonmaru.invcaptive.plugin.InvCaptive
        at com.github.noonmaru.invcaptive.plugin.InvCaptivePlugin.onCommand(InvCaptivePlugin.kt:168) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-342]
        ... 19 more
[11:12:10 INFO]: YouTube_Inix issued server command: /captive YouTube_Inix
[11:12:10 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'captive' in plugin InvCaptive v0.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-342]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-342]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-342]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-342]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.noonmaru.invcaptive.plugin.InvCaptive
        at com.github.noonmaru.invcaptive.plugin.InvCaptivePlugin.onCommand(InvCaptivePlugin.kt:168) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-342]
        ... 19 more
>

**Comment by inchan1832** [comment]
아 그 주신 링크로 서버 열었더니 되는데 영상에 나온 그 깨지는 블럭들이 랜덤으로 안바뀌고 그대로 나오는데 정상인가요

**Comment by devil0414** [comment]
정상입니다. 영상에 나오는 블럭과 다르게 하고 싶으면 플러그인에서의 코드에서 시드를 크게 바꾸시면 됩니다.

**Comment by inchan1832** [comment]
inventory.yml 파일의 어떤 부분에서 시드를 바꿀수 있나요?

**Comment by devil0414** [comment]
inventory.yml이 아니라 플러그인 코드를 말하는 겁니다.

**Comment by qogusdn1017** [comment]
> inventory.yml이 아니라 플러그인 코드를 말하는 겁니다.

그럴필요가 없어보이는게 최근 빌드에 config.yml이 들어가서 그거만 바꿔주면 될듯합니다

**Comment by devil0414** [comment]
넵. 그런 방법도 있었네요.

**Comment by inchan1832** [comment]
> 넵. 그런 방법도 있었네요.

플러그인 소스를 뜯어서 해야하는건가요? 제가 그쪽으로는 잘 몰라서;;

**Comment by qogusdn1017** [comment]
> > 넵. 그런 방법도 있었네요.
> 
> 플러그인 소스를 뜯어서 해야하는건가요? 제가 그쪽으로는 잘 몰라서;;
> 

최신 커밋에서 소스를 Clone하시어 src₩main₩resources 안에있는 config.yml을 수정하시면 됩니다.

~~아마 제 생각에 빌드된거로 서버돌리면 config.yml 생성될거같은데 그걸 확인 못했네요 요즘 일이 많아서...~~
