### ISSUE TITLE
명령어를 실행하면 이상한 문구가뜹니다

### ISSUE THREAD

**Issue by jjm7244** [noonmaru/inv-captive#20]
/captive명령어를 사용하면 이 An internal error occurred while attemping to perform this command문구가 뜹니다 어떻게 해결하나요?

**Comment by qogusdn1017** [comment]
## 답변드리기 앞서서

> Paper가 아닌 다른 서버 구동기를 쓰신다면, 오류가 날 수 있으니 확인 해주세요.

> 의존성 플러그인이 버전에 맞게 들어갔는지 확인 해주세요.

---

## 요청

콘솔 내부의 빨간색 오류 내용 (stacktrace) 첨부 가능하신가요?

**Comment by jjm7244** [comment]
[19:03:07] [Server thread/WARN]: Unexpected exception while parsing console command "captive"
org.bukkit.command.CommandException: Unhandled exception executing command 'captive' in plugin InvCaptive v0.1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:743) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:381) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:350) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R3/PlayerInventory
        at com.github.noonmaru.invcaptive.plugin.InvCaptive.<clinit>(InvCaptive.kt:25) ~[?:?]
        at com.github.noonmaru.invcaptive.plugin.InvCaptivePlugin.onCommand(InvCaptivePlugin.kt:172) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R3.PlayerInventory
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at com.github.noonmaru.invcaptive.plugin.InvCaptive.<clinit>(InvCaptive.kt:25) ~[?:?]
        at com.github.noonmaru.invcaptive.plugin.InvCaptivePlugin.onCommand(InvCaptivePlugin.kt:172) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-2740d5a-890130b]
        ... 9 more

**Comment by qogusdn1017** [comment]
PaperMC를 사용 부탁드립니다!

[페이퍼 1.16.4](https://papermc.io/api/v1/paper/1.16.4/latest/download)

**Comment by qogusdn1017** [comment]
해결되셨다면 이슈 닫아주세요
