### ISSUE TITLE
inv-captive.ps1 실행 오류

### ISSUE THREAD

**Issue by smh6633** [noonmaru/inv-captive#47]
서버가 잘 실행되다가
Loading libraries, please wait...
Failed to start the minecraft server
java.lang.Exception: Failed to load configuration file: bukkit.yml
        at net.minecraft.server.v1_16_R3.Main.loadConfigFile(Main.java:232) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.Main.main(Main.java:68) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.craftbukkit.Main.main(Main.java:276) ~[patched_1.16.4.jar:git-Paper-416]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:58) ~[paper.jar:?]
Caused by: org.bukkit.configuration.InvalidConfigurationException: unacceptable code point '' (0x0) special characters are not allowed
in "'string'", position 0
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.Main.loadConfigFile(Main.java:230) ~[patched_1.16.4.jar:git-Paper-416]
        ... 7 more
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:118) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[patched_1.16.4.jar:git-Paper-416]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:398) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.4.jar:git-Paper-416]
        at net.minecraft.server.v1_16_R3.Main.loadConfigFile(Main.java:230) ~[patched_1.16.4.jar:git-Paper-416]
        ... 7 more
이런 문구가 빨간 글씨로 써지면서 계속 반복되네요

**Comment by chipppppp** [comment]
자바11버전 설치해보세요

**Comment by chipppppp** [comment]
> 자바 11 버전 설치 설치



> 자바 11 버전 설치하시면
될겁니다

**Comment by chipppppp** [comment]
> 자바 11 버전 설치하고 실행
해보시면 될겁니다

**Comment by chipppppp** [comment]
> 자바 11 버전 설치                     해보세요

**Comment by chipppppp** [comment]
자바 11버전 필수입니다

**Comment by ghost** [comment]
> 자바 11버전 필수입니다

Java 버전과는 문제가 없어보입니다

bukkit.yml을 삭제해보시고 다시 서버 돌려보세요

**Comment by Oysfgaq** [comment]
> Java 버전과는 문제가 없어보입니다
> 
> bukkit.yml을 삭제해보시고 다시 서버 돌려보세요

자바 버전과 관련 있는데요 제가 직접 해봤어요
