### ISSUE TITLE
1.16.4버전 BUG

### ISSUE THREAD

**Issue by sswimming** [noonmaru/inv-captive#7]
Could not pass event BlockBreakEvent to InvCaptive v0.0.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:309) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:268) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:238) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1297) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getTranslationKey()Ljava/lang/String;
	at com.github.noonmaru.invcaptive.plugin.InvCaptivePlugin.onBlockBreak(InvCaptivePlugin.kt:119) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-37d799b-3eb7236]
	... 21 more

다른건 정상작동 하지만 블럭을 뿌셔서 인벤토리를 열어도 채팅에 ~~님이 ~~아이템으로 라는 채팅은 안나오고 버킷에 에러코드가 나옵니다.

**Comment by sswimming** [comment]
spigot 버킷 -> paper 버킷 으로 변경하니 해당현상 사라졌습니다.
